In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,auc,roc_auc_score
from sklearn.metrics import recall_score, precision_score, accuracy_score, f1_score

In [102]:
df=pd.read_csv("Churn_Modelling (1).csv")

In [179]:
df.isnull().sum().any()

False

In [104]:
df=df.loc[df["Balance"]>0]

In [105]:
df=df.drop(columns=["Surname","RowNumber","CustomerId"])

In [109]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
4          850     Spain  Female   43       2  125510.82              1   
5          645     Spain    Male   44       8  113755.78              2   
7          376   Germany  Female   29       4  115046.74              4   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
4          1               1         79084.10       0  
5          1               0        149756.71       1  
7          1               0        119346.88       1

In [110]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(categorical_features=[1])


In [114]:
geo=pd.get_dummies(df['Geography'])

In [128]:
df=pd.concat([geo,df],axis=1)

In [130]:
df=df.drop(columns="Geography")


In [133]:
df=pd.concat([pd.get_dummies(df["Gender"]),df],axis=1)

In [140]:
df=df.drop(columns="Gender")

In [137]:
df=df.drop(columns=["France","Female"])

In [173]:
df.to_csv("churn.csv",index=False)

In [142]:
y=df.iloc[:,-1].values

In [147]:
X=df.iloc[:,0:11].values


((6383, 11), array([0, 1, 0, ..., 0, 1, 0], dtype=int64))

In [167]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
                                                    random_state=42, stratify=y)

In [168]:
log=LogisticRegression()

In [169]:
log.fit(X_train,y_train)

D:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [170]:
y_pred=log.predict(X_test)

In [171]:
confusion_matrix(y_test,y_pred)

array([[963,   7],
       [302,   5]], dtype=int64)

In [172]:
print('test-set confusion matrix:\n', confusion_matrix(y_test,y_pred)) 
print("recall score: ", recall_score(y_test,y_pred))
print("precision score: ", precision_score(y_test,y_pred))
print("f1 score: ", f1_score(y_test,y_pred))
print("accuracy score: ", accuracy_score(y_test,y_pred))
print("ROC AUC: {}".format(roc_auc_score(y_test, y_pred_prob[:,1])))

test-set confusion matrix:
 [[963   7]
 [302   5]]
recall score:  0.016286644951140065
precision score:  0.4166666666666667
f1 score:  0.03134796238244514
accuracy score:  0.7580266249021144
ROC AUC: 0.49275999865677156


In [154]:
from sklearn.naive_bayes import GaussianNB
# create classifier
GaussNB = GaussianNB()
# fit it to training data
GaussNB.fit(X_train,y_train)
# predict using test data
y_pred = GaussNB.predict(X_test)
# Compute predicted probabilities: y_pred_prob
y_pred_prob = GaussNB.predict_proba(X_test)
#for fun: train-set predictions
train_pred = GaussNB.predict(X_train)
confusion_matrix(y_test,y_pred)

array([[931,  39],
       [270,  37]], dtype=int64)

In [155]:
print('test-set confusion matrix:\n', confusion_matrix(y_test,y_pred)) 
print("recall score: ", recall_score(y_test,y_pred))
print("precision score: ", precision_score(y_test,y_pred))
print("f1 score: ", f1_score(y_test,y_pred))
print("accuracy score: ", accuracy_score(y_test,y_pred))
print("ROC AUC: {}".format(roc_auc_score(y_test, y_pred_prob[:,1])))

test-set confusion matrix:
 [[931  39]
 [270  37]]
recall score:  0.12052117263843648
precision score:  0.4868421052631579
f1 score:  0.19321148825065274
accuracy score:  0.7580266249021144
ROC AUC: 0.7623761711273045


In [156]:
from sklearn.neighbors import KNeighborsClassifier
# create classifier
knn = KNeighborsClassifier(n_neighbors=7, p=2, metric='minkowski')
# fit it to training data
knn.fit(X_train,y_train)
# predict using test data
y_pred = knn.predict(X_test)
# Compute predicted probabilities: y_pred_prob
y_pred_prob = knn.predict_proba(X_test)
#for fun: train-set predictions
train_pred = knn.predict(X_train)
print('train-set confusion matrix:\n', confusion_matrix(y_train,train_pred))

train-set confusion matrix:
 [[3734  142]
 [1017  213]]


In [157]:
print('test-set confusion matrix:\n', confusion_matrix(y_test,y_pred)) 
print("recall score: ", recall_score(y_test,y_pred))
print("precision score: ", precision_score(y_test,y_pred))
print("f1 score: ", f1_score(y_test,y_pred))
print("accuracy score: ", accuracy_score(y_test,y_pred))
print("ROC AUC: {}".format(roc_auc_score(y_test, y_pred_prob[:,1])))

test-set confusion matrix:
 [[906  64]
 [283  24]]
recall score:  0.0781758957654723
precision score:  0.2727272727272727
f1 score:  0.12151898734177215
accuracy score:  0.7282693813625685
ROC AUC: 0.49275999865677156
